version: '3.8'

services:
  aidevassistant:
    image: aidevassistant

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./backend:/app
    depends_on:
      - frontend
      - postgres

  python-executor:
    image: python:3.9
    volumes:
      - ./backend:/app

  cpp-executor:
    image: gcc:latest
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    command: [ "npm", "start" ]
    volumes:
      - ./frontend:/app

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: code_exec_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
